version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: bot-financeiro-db
    ports:
      - '5959:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot-financeiro
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: