export enum EnvironmentEnums {
    APPLICATION_ENDPOINT = 'APPLICATION_ENDPOINT',
    OPENAI_API_KEY = 'OPENAI_API_KEY',
    DATABASE_URL = 'DATABASE_URL',
    WHATSAPP_API_TOKEN = 'WHATSAPP_API_TOKEN',
    WHATSAPP_VERIFICATION_TOKEN = 'WHATSAPP_VERIFICATION_TOKEN',
    WHATSAPP_NUMBER_ID = 'WHATSAPP_NUMBER_ID',
    TRIGGER_API_KEY = 'TRIGGER_API_KEY',
}
